---
title: "Open procurement data sources"
author: "Viktoriia Poltoratskaia"
date: "`r Sys.Date()`"
output: html_document
---
| Source | Geographic coverage | Time coverage | Regularity of updates | Scope | Format | Is processed? | Replication code available |
|---|---|---|---|---|---|---|---|---|
| [Opentender](https://opentender.eu/all/about/about-opentender) | EU + TED + GE, UK, MK, CH, RS | Depends on country, but up to the beginning of 2025 | 6 months | Transparency + integrity [indicators](https://opentender.eu/all/about/glossary) | json, csv, ocds, ndjson | Yes | No |
| [Global public procurement procedures database](https://www.govtransparency.eu/wp-content/uploads/2024/04/Fazekas-et-al_Global-PP-data_published_2024.pdf) | [1](https://data.mendeley.com/datasets/w9mzf4vswh/3), [2](https://data.mendeley.com/datasets/fwzpywbhgw/3). | IT, USA, AM, AT, BD, BE, BG, BR, CO, CY, CZ, DE, DK, EE, ES, FI, FR, GE, GR, HR, HU, ID, IE, IS, KE, LT, LU, LV, MK, MT, NL, NO, PL, PT, PY, RO, SE, SI, SK, UK, UY  | Depends on country, on average 2006-2021 | So far 1 time thing | Corruption indicators | csv | Yes | No |
| [ProAct](https://www.procurementintegrity.org/data/) | AM, AT, BE, BG, CL, CO, HR, CY, CZ, DK, EE, FI, FR, GE, DE, GR, HU, IS, IN, ID, IE, IT, JM, KE, LV, LT, LU, MK, MT, MX, MD, NL, NO, PY, PL, PT, RO, SK, SI, ES, SE, CH, UG, GB, US, UY | Depends on the country, on average 1990 up to 2020 | Depends on the WB request, last update in 2022 | Competition + transparency + integrity [indicators](https://www.procurementintegrity.org/country/ES) + descriptives by countries (buyers, suppliers, markets, contracts) | csv | Yes | [Yes](https://github.com/INTVP/proACT) (for 2020 BUT input data should be requested separately, so no scraping codes) |
| [Open Contracting](https://data.open-contracting.org/en/search/) | AL, AR, AM, AU, AT, BE, BO, BG, CA, CL, CO, CR, HR, CY, CZ, DK, DO, EC, EE, FI, FR, GE, DE, GH, GR, GT, HN, HU, IS, IN, ID, IE, IT, KE, LT, LU, MT, MX, NP, NL, NI, NG, NO, PY, PE, PL, PT, RO, RW, SK, SI, ZA, ES, SE, CH, UG, UA, GB, US, UY, ZM | Depends on the country, on average 2005-2023 | Depends on the country, majority by request and less than half every 6 months  | Don’t implement indicators automatically, they have [suggestions](https://www.open-contracting.org/data/data-use/) which could be implemented if the data is in ocds format. Eg [red flags for integrity](https://www.open-contracting.org/wp-content/uploads/2024/12/OCP2024-RedFlagProcurement-1.pdf), or [market performance](https://docs.google.com/document/d/1vSJk9-qWSTQEx9ZZc7BUhQZMHvTRcyDYVS2sl8HB__k/edit?tab=t.0#heading=h.6w0z58d8gukb), or [sustainability](https://docs.google.com/document/d/1YwFhuMJ3ALKOch7eCJ6ELv6gbA5cEZlxpzYx_bJddwk/edit?tab=t.0#heading=h.obadqo9ivs50). Yet these indicators are not validated against proxies => we don’t know if these indicators actually work + they are not very flexible / adjustable. | сsv, excel, json | Yes and no. Eg all OpenTender countries are republished from OpenTender but in non-flattened format. The rest is pretty much raw unfiltered data separated into respective fields with some basic touch-ups. | Yes, there is a code to [download](https://kingfisher-collect.readthedocs.io/en/latest/) data (only for data in OCDS format) |
| FCDO/DFID low and middle-income [datasets](https://www.govtransparency.eu/global-public-procurement-dataset-selected-low-and-middle-income-country-datasets/) | CL, CO, IN, ID, JM, KE, MX, PY, UG, UY | Depends on the country, on average ~2010-2019 | One time thing | Corruption | dta, csv | Yes | [Yes](https://github.com/GovTransparencyInstitue/dfid2_update2021) |
| TED (tenders electronic daily) | EU + EEA + CH + GB + Candidates + (above threshold) | 2015-2025 | Daily | No indicators | xml | No, but fields are standardized for countries  | - |
| World Bank Projects [Procurement data](https://projects.worldbank.org/en/projects-operations/procurement?showrecent=true&srce=notices) | IN, ET, MG, NG, PK, BD, LK, MZ, KE, BO, CD, ID, BR, KG, CI, CN, CM, PH, MW, VN, GH, AR, BF, NE, SO, TZ, UZ, BI, TR, SN, KH, CO, NI, CG, HN, NP, UG, AO, PE, LA, AF, AM, MD, TJ, ML, BJ, LR, RW, UA, PS, CF, MN, KM, TD, LS, RS, SB, MR, EC, SV, GE, ZM, HT, GN, SL, RO, BA, EG, DO, DJ, JO, MM, TN, BT, MX, MV, GM, GY, BY, UY, MK, TO, LB, GA, IQ, PY, AZ, TG, VC, XK, HR, AL, JM, PG, KZ, ST, MA, RU, CV, SS, MH, FM, SZ, WS, KI, TL, DM, GT, GW, BZ, TV, PA, ZW, SD, LC, CR, ZA, YE, CL, VU, ME, PL, TR, FJ, BW, SR, BG, GD, IR, MU, TT, SC, NA, ER, KR, BB, DZ, PW, HU, AG, TM (many countries have < 100 notices) | 2005-2025 | As soon as new notice is published | No indicators | excel | No, but fields are standardized  | - |

