---
title: "proc_ind_ex"
author: "Viktoriia Poltoratskaia"
date: "2025-12-24"
output: html_document
---
## Examples of public procurement indicators

| Indicators type | Source(s) | Are validated? | Which data needed | Why are these indicators interesting to countries? |
|---|---|---|---|---|
| Corruption, fraud, collusion | 1. [WB GRAS](https://www.govtransparency.eu/wp-content/uploads/2023/11/WBG-GRAS-Fazekas-Vaz-Mondo-T%C3%B3th.pdf);<br>2. [OpenTender](https://opentender.eu/start);<br>3. [ProAct](https://www.procurementintegrity.org/contracts) | 1. Some yes, a lot of indicators are proposed as possible but not checked<br>2. Integrity indicators are validated<br>3. Integrity indicators are validated | 1. Procurement (full), company register, PEP/asset declarations, data on company ownership, performance data<br>2. Full procurement data, company data (e.g., company registration, ownership, financials, etc)<br>3. Bidders country, tender final price, buyer id/name, delivery date | - Cost of corruption  governments want to spend less. Example in WB study on Bangladesh, reforms to procurement may reduce costs.  [Example](https://www.govtransparency.eu/wp-content/uploads/2023/04/e-procurement_bangladesh_wp_WB_April2023.pdf). |
| Sustainability | 1. OCDS data [SPP guide](https://docs.google.com/document/d/1YwFhuMJ3ALKOch7eCJ6ELv6gbA5cEZlxpzYx_bJddwk/edit?tab=t.0);<br>2. [UN GM criteria](https://www.ungm.org/Shared/KnowledgeCenter/Pages/SustProcIndicators);<br>3. OECD report (chapter 3): [SDG 12.7 target and indicators](https://www.unep.org/explore-topics/resource-efficiency/what-we-do/sustainable-public-procurement/sdg-127-target-and);<br>4. [WB study](https://openknowledge.worldbank.org/server/api/core/bitstreams/1dc44c28-0540-4627-af1b-010121b5d811/content) and [study](https://www.sciencedirect.com/science/article/pii/S1478409220300807?via%3Dihub) on Belgian public procurement | 1. No (eg list of key words for criteria as well as comparison measures from year to year) + closer to qualitative assessment<br>2. No<br>3. Yes<br>4. Unclear | 1. Procurement data with full award criteria, technical specifications and evaluation reports. This is only possible if a country has OCDS format and has full contracting cycle public. If data is limited to tender announcement and award, it is likely not possible<br>2. Tender requirements and/or evaluation reports<br>3. Procurement data with full contracting cycle (award criteria + technical specifications + info on contract implementation and requirements)<br>4. Technical specifications, award criteria | - Sustainable procurement boosts firms productivity. [Example 1](https://openknowledge.worldbank.org/server/api/core/bitstreams/1dc44c28-0540-4627-af1b-010121b5d811/content), [Example 2](https://journals.sagepub.com/doi/pdf/10.1177/1023263X211016756)) |
| Market efficiency | 1. OCDS [market performance indicators](https://docs.google.com/document/d/1vSJk9-qWSTQEx9ZZc7BUhQZMHvTRcyDYVS2sl8HB__k/edit?tab=t.0#heading=h.6w0z58d8gukb)<br>2. [European Commissions report](https://ec.europa.eu/regional_policy/sources/work/201703_regional_pp_governance.pdf)<br>3. [GPPOI (GTI)](https://www.govtransparency.eu/wp-content/uploads/2021/09/Ada...ormatted_2.pdf#:~:text=A%20high%20GPPOI%20indicates%20that,see)<br>4. [Single Market Scoreboard](https://single-market-scoreboard.ec.europa.eu/business-framew...rded%20without%20prior,is%20clearly%20room%20for%20improvement)<br>5. GPPD [pricing efficiency](https://openknowledge.worldbank.org/server/api/core/bitstreams/bd31ce7f-96f9-4e98-8cdd-a87488625e8e/content) | 1. No<br>2. Yes<br>3. No<br>4. No<br>5. Yes | 1. Bidders, number of bids, CPV codes + prices, buyers, loosing bids. Need full bidding information. Some countries don’t provide it<br>2. Winners and buyers, plus procurement procedure type, length of procedure, number of bidders. Availability depends on the available info in the data<br>3. Procurement (full), company register, PEP/asset declarations, data on company ownership, performance data<br>4. EU specific info is needed (contract value, contract duration, contract modifications, implementation date, procedure type, number of bids/bidders | - Market efficiency is positively correlated with quality of governance and economic growth. Example studies [1](https://www.jstor.org/stable/pdf/10.1086/345578.pdf), [2](https://www.jstor.org/stable/pdf/25592509.pdf). |
| Transparency | 1. [European Commissions study](https://ec.europa.eu/regional_policy/sources/work/201703_regional_pp_governance.pdf)<br>2. [Single Market Scoreboard](https://single-market-scoreboard.ec.europa.eu/business-framew...rded%20without%20prior,is%20clearly%20room%20for%20improvement)<br>3. [OpenTender](https://opentender.eu/start)<br>4. WB [GPPD](https://www.globalpublicprocurementdata.org/) | 1. Yes<br>2. No<br>3. No<br>4. No | Calculated either as share of missing info per variables / buyer or as binary (present/absent info) | - Publicity decreases costs of procurement. Example study [1](https://www.jstor.org/stable/pdf/10.1086/345578.pdf), study [2](https://www.imf.org/en/Publications/WP/Issues/2022/10/06/Procurement-and-Growth-Institutional-Quality-and-the-Mechanisms-in-Developing-525389), [study 3](https://www.govtransparency.eu/wp-content/uploads/2023/06/GTI_pharmaceutical_analysis_230602_GTI_WP_2023_04.pdf), [study 4](https://www.govtransparency.eu/wp-content/uploads/2020/10/IMF_wpiea2022094-print-pdf.pdf?utm_source=web&utm_medium=IMF&utm_content=EDP&utm_campaign=EDP) |

