---
title: "qual_assessment"
author: "Viktoriia Poltoratskaia"
date: "2025-12-24"
output: html_document
---
## Qualitative assessments of public procurement systems

## Qualitative assessments of public procurement systems

| Source | Type of review | PP characteristics reviewed |
|---|---|---|
| **WB–OECD [MAPS](https://www.mapsinitiative.org/en/methodology.html)** ([example report](https://www.mapsinitiative.org/content/dam/maps-initiative/en/assessments/ethiopia/maps-assessment-ethiopia-main-report.pdf)) | Legal, regulatory, and policy frameworks | Institutional framework and management capacity, procurement operations and market practices, accountability, integrity, and transparency mechanisms |
| **[EuroPAM](https://europam.eu/data/in-law%20indicators/EuroPAM%20Public%20Procurement%20indicator%20list.pdf)** ([scoring system](https://europam.eu/data/in-law%20indicators/EuroPAM%20Scoring%20Framework.pdf)) | Legal / regulatory | Scope, thresholds, transparency, competition, evaluation, institutional setup, and complaint mechanisms |
| **OECD [Public Procurement Performance](https://www.oecd.org/content/dam/oecd/en/publications/reports/2023/08/public-procurement-performance_0ebfe3e7/0dde73f4-en.pdf)** | Semi-quant reviews of regulations implementation | Transparency, publication, sanctions, audit, integrity, payments, efficiency, professionalization, digitalization, GPP, SME |
| **SIGMA [Public Procurement Briefs](https://www.sigmaweb.org/en/publications/sigma-public-procurement-briefs_23109246.html)** | Regulatory + institutional setup | Scope and thresholds, planning, procedures, competition and SME access, qualification and exclusion of bidders, award criteria and evaluation, life-cycle costing, modifications, framework agreements and central purchasing, e-procurement, monitoring, audit, PPPs, sustainability |
| **[Bosio et al.](https://www.nber.org/system/files/working_papers/w27188/w27188.pdf)** | Comparative expert analysis | Regulatory dimensions (transparency, competition, limits to exclusion, integrity of contracts) |

